blank_issues_enabled: true
contact_links:
  - name: Suggest a new name for PebbleNTN
    url: https://github.com/optio/PebbleNTN/discussions/45
    about: Post a name idea, or upvote the ones you like.
